"""Build our own copy of the blog (blog.greencube.app/blog/...) from the saved posts.

    python3 -I blog-archive/tools/build_blog.py            (run from the repo root)

Reads blog-archive/ (index.json, posts/, images/) and writes blog/:
one page per post at the same address BabyLoveGrowth used, the list page,
a sitemap, a shared stylesheet and resized images. Safe to re-run: blog/ is
rebuilt from scratch every time, so new posts saved later go through the
same fixes.
"""
import html, json, os, re, shutil, sys
from datetime import date
from PIL import Image

sys.path.insert(0, os.path.dirname(__file__))
import facts

SRC, OUT = 'blog-archive', 'blog'
HOST = 'https://blog.greencube.app'
TODAY = date.today().isoformat()
MAX_W = 1200

idx = json.load(open(f'{SRC}/index.json', encoding='utf-8'))
idx.sort(key=lambda p: (p['date_published'] or p['sitemap_lastmod'] or ''), reverse=True)

shutil.rmtree(OUT, ignore_errors=True)
os.makedirs(f'{OUT}/images')
shutil.copy(os.path.join(os.path.dirname(__file__), 'blog.css'), f'{OUT}/blog.css')

# ---------- images: max 1200 px wide, real JPEG unless it needs transparency ----------
sizes = {}
def image(rel):
    """rel is 'images/<name>' from the archive; returns (published path, w, h)."""
    if rel in sizes: return sizes[rel]
    name = os.path.basename(rel)
    im = Image.open(f'{SRC}/{rel}')
    alpha = im.mode in ('RGBA', 'LA') or (im.mode == 'P' and 'transparency' in im.info)
    if im.width > MAX_W:
        im = im.resize((MAX_W, round(im.height * MAX_W / im.width)), Image.LANCZOS)
    base = os.path.splitext(name)[0]
    if alpha:
        out = base + '.png'; im.save(f'{OUT}/images/{out}', optimize=True)
    else:
        out = base + '.jpg'; im.convert('RGB').save(f'{OUT}/images/{out}', 'JPEG', quality=80, optimize=True, progressive=True)
    sizes[rel] = (f'/blog/images/{out}', im.width, im.height)
    return sizes[rel]

def cf_email(hexs):
    k = int(hexs[:2], 16)
    return ''.join(chr(int(hexs[i:i + 2], 16) ^ k) for i in range(2, len(hexs), 2))

# ---------- body clean-up ----------
def clean(body):
    body = body.replace(' node="[object Object]"', '')
    body = body.replace('<div class="my-4 w-full overflow-x-auto">', '<div class="tbl-wrap">')
    body = body.replace(' class="min-w-full border-collapse"', '')
    # Cloudflare's email obfuscation mangled "python@3.11" into a fake email link
    body = re.sub(r'<a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="([0-9a-f]+)">[^<]*</a>',
                  lambda m: html.escape(cf_email(m.group(1))), body)
    # BabyLoveGrowth's links to its own tools: keep the words, drop the link
    body = re.sub(r'<p><a [^>]*href="https://(www\.)?babylovegrowth\.ai/?"[^>]*>Article generated by BabyLoveGrowth</a></p>\n?', '', body)
    body = re.sub(r'<a [^>]*href="https://(www\.)?babylovegrowth\.ai[^"]*"[^>]*>([\s\S]*?)</a>', r'\2', body)
    def img(m):
        tag = m.group(0)
        src = re.search(r'src="([^"]+)"', tag).group(1)
        if not src.startswith('images/'): return tag
        path, w, h = image(src)
        alt = re.search(r'alt="([^"]*)"', tag)
        return f'<img src="{path}" alt="{alt.group(1) if alt else ""}" width="{w}" height="{h}" loading="lazy" decoding="async"/>'
    return re.sub(r'<img\b[^>]*>', img, body)

NOTE_PARTS = {
    'models': 'today GreenCube picks the right AI model for your computer automatically, '
              'instead of the two models (&ldquo;Quick&rdquo; and &ldquo;All-rounder&rdquo;) described below',
    'account': 'today you sign in once with Google or Microsoft to activate it, and the first launch downloads the AI model; '
               'after that it works offline and your chats and files never leave your PC',
}

def note(kinds):
    if not kinds: return ''
    parts = [NOTE_PARTS[k] for k in kinds]
    text = parts[0][0].upper() + parts[0][1:] + ('. Also, ' + parts[1].replace('today you', 'you') if len(parts) > 1 else '')
    return ('<aside class="update" role="note"><strong>Updated October 2026</strong>'
            '<p>Parts of this article describe an earlier version of GreenCube. ' + text + '. '
            'It costs &euro;9.99 (US$9.99), paid once. '
            '<a href="https://greencube.app/what-you-get">Check what runs on your PC</a></p></aside>')

def nice_date(iso):
    d = date.fromisoformat(iso[:10]); return f'{d.day} {d.strftime("%B %Y")}'

def esc(s): return html.escape(s, quote=True)

HEAD = open(os.path.join(os.path.dirname(__file__), 'blog_shell.html'), encoding='utf-8').read()
shell_top, shell_bottom = HEAD.split('<!-- CONTENT -->')

def page(title, desc, url, og_image, ld, content, og_type='article'):
    top = (shell_top.replace('{{TITLE}}', esc(title)).replace('{{DESC}}', esc(desc))
           .replace('{{URL}}', url).replace('{{OG_IMAGE}}', og_image).replace('{{OG_TYPE}}', og_type)
           .replace('{{LD}}', '\n'.join(f'  <script type="application/ld+json">{json.dumps(x, ensure_ascii=False)}</script>' for x in ld)))
    return top + content + shell_bottom

report = []
listing = []
for p in idx:
    slug = p['slug']
    raw = open(f'{SRC}/posts/{slug}.html', encoding='utf-8').read()
    kinds = facts.notes_for(p['title'] + '\n' + raw + '\n' + '\n'.join(f['q'] + ' ' + f['a'] for f in p['faq']))
    body, ch1 = facts.fix_text(clean(raw))
    title, ch2 = facts.fix_text(p['title'])
    desc, ch3 = facts.fix_text(p['description'] or '')
    faq = []
    for f in p['faq']:
        q, _ = facts.fix_text(f['q']); a, _ = facts.fix_text(f['a']); faq.append((q, a))
    changed = bool(ch1 or ch2 or ch3 or kinds)
    published = (p['date_published'] or p['sitemap_lastmod'])[:10]
    modified = TODAY if changed else (p['date_modified'] or p['sitemap_lastmod'] or published)[:10]
    url = f'{HOST}/blog/{slug}'
    cover = image(p['cover_image']) if p['cover_image'] else None
    og = HOST + cover[0] if cover else 'https://greencube.app/og.jpg'
    ld = [{
        '@context': 'https://schema.org', '@type': 'BlogPosting', 'headline': title, 'description': desc,
        'image': og, 'datePublished': published, 'dateModified': modified, 'inLanguage': 'en',
        'mainEntityOfPage': url,
        'author': {'@type': 'Organization', 'name': 'GreenCube', 'url': 'https://greencube.app'},
        'publisher': {'@type': 'Organization', 'name': 'GreenCube', 'url': 'https://greencube.app',
                      'logo': {'@type': 'ImageObject', 'url': 'https://greencube.app/icon-512.png'}},
    }]
    if faq:
        ld.append({'@context': 'https://schema.org', '@type': 'FAQPage', 'mainEntity': [
            {'@type': 'Question', 'name': q, 'acceptedAnswer': {'@type': 'Answer', 'text': a}} for q, a in faq]})
    byline = f'GreenCube &middot; {nice_date(published)}' + (f' &middot; updated {nice_date(modified)}' if modified != published and changed else '')
    content = (
        f'<article>\n<p class="kicker"><a href="/blog">GreenCube blog</a></p>\n<h1>{esc(title)}</h1>\n'
        f'<p class="byline">{byline}</p>\n{note(kinds)}\n'
        + (f'<img class="cover" src="{cover[0]}" alt="{esc(p["cover_alt"] or "")}" width="{cover[1]}" height="{cover[2]}" fetchpriority="high"/>\n' if cover else '')
        + body +
        '\n<div class="cta-box"><h3>Your own AI, on your own PC</h3>'
        '<p>GreenCube runs on your computer: no usage limits, no subscription, works without internet. &euro;9.99, paid once.</p>'
        '<a class="cta" href="https://greencube.app/buy">Get GreenCube <span aria-hidden="true">&rarr;</span></a></div>\n</article>\n')
    open(f'{OUT}/{slug}.html', 'w', encoding='utf-8').write(page(f'{title} | GreenCube blog', desc, url, og, ld, content))
    listing.append((slug, title, desc, published, modified))
    report.append({'slug': slug, 'note': kinds, 'text_fixes': [list(c) for c in ch1 + ch2 + ch3]})

# ---------- the list page ----------
items = '\n'.join(
    f'<li><a href="/blog/{s}"><span class="date">{nice_date(pub)}</span><h2>{esc(t)}</h2><p>{esc(d)}</p></a></li>'
    for s, t, d, pub, _ in listing)
content = ('<article class="list">\n<p class="kicker">GreenCube blog</p>\n<h1>Guides and comparisons</h1>\n'
           '<p class="lede">Running AI on your own computer: tools, models, hardware and privacy.</p>\n'
           f'<ul class="posts">\n{items}\n</ul>\n</article>\n')
open(f'{OUT}/index.html', 'w', encoding='utf-8').write(page(
    'GreenCube blog: guides and comparisons', 'Guides and comparisons about running AI on your own computer: tools, models, hardware and privacy.',
    f'{HOST}/blog', 'https://greencube.app/og.jpg',
    [{'@context': 'https://schema.org', '@type': 'Blog', 'name': 'GreenCube blog', 'url': f'{HOST}/blog'}], content, og_type='website'))

# ---------- sitemap ----------
urls = [f'  <url><loc>{HOST}/blog</loc><lastmod>{max(l[4] for l in listing)}</lastmod></url>'] + \
       [f'  <url><loc>{HOST}/blog/{s}</loc><lastmod>{m}</lastmod></url>' for s, _, _, _, m in listing]
open(f'{OUT}/sitemap.xml', 'w', encoding='utf-8').write(
    '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + '\n'.join(urls) + '\n</urlset>\n')

json.dump(report, open(f'{SRC}/build-report.json', 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
mb = sum(os.path.getsize(f'{OUT}/images/{f}') for f in os.listdir(f'{OUT}/images')) / 1e6
print(f'{len(listing)} posts, {len(os.listdir(OUT + "/images"))} images ({mb:.1f} MB), '
      f'{sum(1 for r in report if r["note"])} with an update note, {sum(1 for r in report if r["text_fixes"])} with text fixes')
